
name: "fastertransformer"
backend: "fastertransformer"
default_model_filename: "gpt3_89B"
max_batch_size: 8
input [
  {
    name: "INPUT_ID"
    data_type: TYPE_UINT32
    dims: [ -1 ]
  },
  {
    name: "REQUEST_INPUT_LEN"
    data_type: TYPE_UINT32
    dims: [ 1 ]
  },
  {
    name: "REQUEST_OUTPUT_LEN"
    data_type: TYPE_UINT32
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_UINT32
    dims: [ -1 ]
  }
]
instance_group [
  {
    count: 1
    kind : KIND_CPU
  }
]

parameters {
  key: "candidate_num"
  value: {
    string_value: "1"
  }
}
parameters {
  key: "probability_threshold"
  value: {
    string_value: "0.0"
  }
}
parameters {
  key: "tensor_para_size"
  value: {
    string_value: "8"
  }
}
parameters {
  key: "layer_para_size"
  value: {
    string_value: "1"
  }
}
parameters {
  key: "layer_para_batch_size"
  value: {
    string_value: "8"
  }
}
parameters {
  key: "max_seq_len"
  value: {
    string_value: "544"
  }
}
parameters {
  key: "is_half"
  value: {
    string_value: "1"
  }
}
parameters {
  key: "head_num"
  value: {
    string_value: "96"
  }
}
parameters {
  key: "size_per_head"
  value: {
    string_value: "128"
  }
}
parameters {
  key: "vocab_size"
  value: {
    string_value: "51200"
  }
}
parameters {
  key: "decoder_layers"
  value: {
    string_value: "48"
  }
}
parameters {
  key: "model_name"
  value: {
    string_value: "gpt3_89B"
  }
}
parameters {
  key: "batch_size"
  value: {
    string_value: "8"
  }
}
parameters {
  key: "is_fuse_QKV"
  value: {
    string_value: "1"
  }
}
parameters {
  key: "temperature"
  value: {
    string_value: "1.0"
  }
}
parameters {
  key: "repetition_penalty"
  value: {
    string_value: "1.0"
  }
}

